"""
Assignment 2 - RL Algorithm Comparison
SUBMISSION FILE: assignment2_024954471.py

Rules:
1. Submit ONE .py file only. Do not submit notebooks, PDFs, Word files, ZIP files, images, or data folders.
2. The file must run from start to finish with: python assignment2_024954471.py
3. Do not use input(). All parameters must be defined in CONFIG below.
4. Do not hard-code final results. Results must be generated by running the algorithms.
5. Keep all required function names exactly as written. The automatic checker will look for them.
6. You may add helper functions/classes, but do not remove the required functions.

Allowed libraries: numpy, random, time, math, collections, matplotlib
Optional: pandas is allowed only for internal tables, not required.
"""

import time
import math
import random
from collections import defaultdict

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


# ============================================================
# 0. STUDENT DETAILS
# ============================================================
STUDENT_ID = "024954471"
STUDENT_NAME = "Doron Peleg"
ENVIRONMENT_NAME = "Stochastic Treasure Hunt GridWorld"


# ============================================================
# 1. CONFIGURATION
# ============================================================
CONFIG = {
    "seed": 42,
    "gamma": 0.9,
    "alpha": 0.1,
    "epsilon": 0.1,
    "lambda_values": [0.2, 0.5, 0.8],
    "num_episodes": 2000,
    "max_steps_per_episode": 200,
    "eval_episodes": 100,
    "make_plots": True,
}


def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)


# ============================================================
# 2. ENVIRONMENT
# ============================================================
UP, DOWN, LEFT, RIGHT = 0, 1, 2, 3
ACTION_DELTAS = {UP: (-1, 0), DOWN: (1, 0), LEFT: (0, -1), RIGHT: (0, 1)}
PERPENDICULAR = {
    UP: [LEFT, RIGHT],
    DOWN: [LEFT, RIGHT],
    LEFT: [UP, DOWN],
    RIGHT: [UP, DOWN],
}


class CustomEnvironment:
    """
    Stochastic Treasure Hunt GridWorld (6x6).

    The agent starts at (0,0) and must reach the treasure at (5,5).
    Walls block movement; traps end the episode with negative reward.
    Transitions are stochastic: 80% intended direction, 10% each perpendicular.

    Layout:
        S  .  .  W  .  .
        .  W  .  .  .  T
        .  .  .  .  .  .
        .  .  W  .  .  .
        .  T  .  .  W  .
        .  .  .  .  .  G

    S=Start, G=Goal(+10), W=Wall, T=Trap(-5), .=Empty(-0.1 step cost)
    """

    ROWS, COLS = 6, 6
    START = (0, 0)
    GOAL = (5, 5)
    WALLS = frozenset({(0, 3), (1, 1), (3, 2), (4, 4)})
    TRAPS = frozenset({(1, 5), (4, 1)})
    STEP_REWARD = -0.1
    GOAL_REWARD = 10.0
    TRAP_REWARD = -5.0
    SLIP_PROB = 0.8

    def __init__(self):
        self.states = [
            (r, c)
            for r in range(self.ROWS)
            for c in range(self.COLS)
            if (r, c) not in self.WALLS
        ]
        self.actions = [UP, DOWN, LEFT, RIGHT]
        self.terminal_states = self.TRAPS | {self.GOAL}
        self.current_state = None

    def reset(self):
        self.current_state = self.START
        return self.current_state

    def _move(self, state, action):
        dr, dc = ACTION_DELTAS[action]
        nr, nc = state[0] + dr, state[1] + dc
        if 0 <= nr < self.ROWS and 0 <= nc < self.COLS and (nr, nc) not in self.WALLS:
            return (nr, nc)
        return state

    def _get_reward(self, next_state):
        if next_state == self.GOAL:
            return self.GOAL_REWARD
        if next_state in self.TRAPS:
            return self.TRAP_REWARD
        return self.STEP_REWARD

    def step(self, action):
        state = self.current_state
        rand_val = random.random()
        if rand_val < self.SLIP_PROB:
            next_state = self._move(state, action)
        elif rand_val < self.SLIP_PROB + 0.1:
            next_state = self._move(state, PERPENDICULAR[action][0])
        else:
            next_state = self._move(state, PERPENDICULAR[action][1])

        reward = self._get_reward(next_state)
        done = next_state in self.terminal_states
        self.current_state = next_state
        return next_state, reward, done, {}

    def get_states(self):
        return list(self.states)

    def get_actions(self, state):
        if state in self.terminal_states:
            return []
        return list(self.actions)

    def get_transition_model(self):
        """
        Return transition model for Dynamic Programming.
        Format: model[state][action] = [(probability, next_state, reward, done), ...]
        """
        model = {}
        for state in self.states:
            if state in self.terminal_states:
                continue
            model[state] = {}
            for action in self.actions:
                transitions = []
                ns = self._move(state, action)
                transitions.append(
                    (self.SLIP_PROB, ns, self._get_reward(ns), ns in self.terminal_states)
                )
                for perp in PERPENDICULAR[action]:
                    ns_p = self._move(state, perp)
                    transitions.append(
                        (0.1, ns_p, self._get_reward(ns_p), ns_p in self.terminal_states)
                    )
                model[state][action] = transitions
        return model


# ============================================================
# 3. POLICY HELPERS
# ============================================================
def epsilon_greedy_action(Q, env, state, epsilon):
    """Choose an action using epsilon-greedy policy with random tie-breaking."""
    actions = env.get_actions(state)
    if not actions:
        return None
    if random.random() < epsilon:
        return random.choice(actions)
    q_values = [Q[(state, a)] for a in actions]
    max_q = max(q_values)
    best_actions = [a for a, q in zip(actions, q_values) if abs(q - max_q) < 1e-10]
    return random.choice(best_actions)


def greedy_policy_from_Q(Q, env):
    """Return deterministic greedy policy from Q."""
    policy = {}
    for state in env.get_states():
        actions = env.get_actions(state)
        if len(actions) == 0:
            continue
        policy[state] = max(actions, key=lambda a: Q[(state, a)])
    return policy


def evaluate_policy(env, policy, episodes=100, max_steps=200, gamma=0.9):
    """Return average discounted return of a policy."""
    returns = []
    for _ in range(episodes):
        state = env.reset()
        G = 0.0
        discount = 1.0
        for _ in range(max_steps):
            action = policy.get(state, None)
            if action is None:
                actions = env.get_actions(state)
                if not actions:
                    break
                action = random.choice(actions)
            next_state, reward, done, info = env.step(action)
            G += discount * reward
            discount *= gamma
            state = next_state
            if done:
                break
        returns.append(G)
    return float(np.mean(returns)) if returns else 0.0


def smooth_rewards(rewards, window=50):
    """Moving average smoothing for plotting."""
    if len(rewards) < window:
        return np.array(rewards)
    return np.convolve(rewards, np.ones(window) / window, mode="valid")


def estimate_convergence(rewards, window=50):
    """Estimate convergence episode: first episode where smoothed reward is within 10% of final avg."""
    smoothed = smooth_rewards(rewards, window)
    if len(smoothed) < window:
        return len(rewards)
    final_avg = np.mean(smoothed[-window:])
    threshold = max(abs(final_avg) * 0.1, 0.5)
    for i, val in enumerate(smoothed):
        if abs(val - final_avg) < threshold:
            return i + window
    return len(rewards)


# ============================================================
# 4. REQUIRED ALGORITHMS
# ============================================================
def run_dynamic_programming(env, gamma=0.9, theta=1e-6, max_iterations=10000):
    """
    Value Iteration: compute optimal V and derive greedy policy.
    Return a dict with keys: V, policy, episodes_rewards, runtime.
    """
    start_time = time.time()
    model = env.get_transition_model()
    states = env.get_states()
    V = {s: 0.0 for s in states}

    for _ in range(max_iterations):
        delta = 0.0
        for state in states:
            actions = env.get_actions(state)
            if not actions:
                continue
            old_v = V[state]
            V[state] = max(
                sum(
                    p * (r + (0.0 if d else gamma * V[ns]))
                    for p, ns, r, d in model[state][a]
                )
                for a in actions
            )
            delta = max(delta, abs(V[state] - old_v))
        if delta < theta:
            break

    policy = {}
    for state in states:
        actions = env.get_actions(state)
        if not actions:
            continue
        policy[state] = max(
            actions,
            key=lambda a: sum(
                p * (r + (0.0 if d else gamma * V[ns]))
                for p, ns, r, d in model[state][a]
            ),
        )

    episodes_rewards = []
    for _ in range(CONFIG["num_episodes"]):
        state = env.reset()
        ep_reward = 0.0
        for _ in range(CONFIG["max_steps_per_episode"]):
            action = policy.get(state)
            if action is None:
                break
            state, reward, done, _ = env.step(action)
            ep_reward += reward
            if done:
                break
        episodes_rewards.append(ep_reward)

    runtime = time.time() - start_time
    return {"V": V, "policy": policy, "episodes_rewards": episodes_rewards, "runtime": runtime}


def run_monte_carlo(env, gamma=0.9, epsilon=0.1, num_episodes=1000, max_steps=200):
    """
    First-visit Monte Carlo control with constant-alpha updates and epsilon-greedy policy.
    Uses incremental Q updates (alpha step size) instead of simple averaging,
    which tracks the improving policy better during on-policy control.
    Return a dict with keys: Q or V, policy, episodes_rewards, runtime.
    """
    start_time = time.time()
    Q = defaultdict(float)
    alpha = CONFIG["alpha"]
    episodes_rewards = []

    for _ in range(num_episodes):
        state = env.reset()
        episode = []
        ep_reward = 0.0

        for _ in range(max_steps):
            action = epsilon_greedy_action(Q, env, state, epsilon)
            next_state, reward, done, _ = env.step(action)
            episode.append((state, action, reward))
            ep_reward += reward
            state = next_state
            if done:
                break
        episodes_rewards.append(ep_reward)

        G = 0.0
        visited = set()
        for s, a, r in reversed(episode):
            G = gamma * G + r
            if (s, a) not in visited:
                visited.add((s, a))
                Q[(s, a)] += alpha * (G - Q[(s, a)])

    policy = greedy_policy_from_Q(Q, env)
    runtime = time.time() - start_time
    return {"Q": dict(Q), "policy": policy, "episodes_rewards": episodes_rewards, "runtime": runtime}


def run_td0(env, gamma=0.9, alpha=0.1, num_episodes=1000, max_steps=200):
    """
    TD(0) value prediction with epsilon-greedy behavior policy.
    Uses the transition model to derive actions from V.
    Return a dict with keys: V, policy, episodes_rewards, runtime.
    """
    start_time = time.time()
    V = defaultdict(float)
    model = env.get_transition_model()
    epsilon = CONFIG["epsilon"]
    episodes_rewards = []

    def _best_action(st):
        acts = env.get_actions(st)
        if not acts:
            return None
        return max(
            acts,
            key=lambda a: sum(
                p * (r + (0.0 if d else gamma * V[ns]))
                for p, ns, r, d in model[st][a]
            ),
        )

    for _ in range(num_episodes):
        state = env.reset()
        ep_reward = 0.0
        for _ in range(max_steps):
            actions = env.get_actions(state)
            if not actions:
                break
            if random.random() < epsilon:
                action = random.choice(actions)
            else:
                action = _best_action(state)
            next_state, reward, done, _ = env.step(action)
            td_target = reward + (0.0 if done else gamma * V[next_state])
            V[state] += alpha * (td_target - V[state])
            ep_reward += reward
            state = next_state
            if done:
                break
        episodes_rewards.append(ep_reward)

    policy = {}
    for state in env.get_states():
        action = _best_action(state)
        if action is not None:
            policy[state] = action

    runtime = time.time() - start_time
    return {"V": dict(V), "policy": policy, "episodes_rewards": episodes_rewards, "runtime": runtime}


def run_q_learning(env, gamma=0.9, alpha=0.1, epsilon=0.1, num_episodes=1000, max_steps=200):
    """
    Off-policy Q-Learning with epsilon-greedy exploration.
    Return a dict with keys: Q, policy, episodes_rewards, runtime.
    """
    start_time = time.time()
    Q = defaultdict(float)
    episodes_rewards = []

    for _ in range(num_episodes):
        state = env.reset()
        ep_reward = 0.0
        for _ in range(max_steps):
            action = epsilon_greedy_action(Q, env, state, epsilon)
            next_state, reward, done, _ = env.step(action)
            next_actions = env.get_actions(next_state)
            max_q_next = max((Q[(next_state, a)] for a in next_actions), default=0.0)
            Q[(state, action)] += alpha * (
                reward + gamma * max_q_next - Q[(state, action)]
            )
            ep_reward += reward
            state = next_state
            if done:
                break
        episodes_rewards.append(ep_reward)

    policy = greedy_policy_from_Q(Q, env)
    runtime = time.time() - start_time
    return {"Q": dict(Q), "policy": policy, "episodes_rewards": episodes_rewards, "runtime": runtime}


def run_sarsa(env, gamma=0.9, alpha=0.1, epsilon=0.1, num_episodes=1000, max_steps=200):
    """
    On-policy SARSA with epsilon-greedy policy.
    Return a dict with keys: Q, policy, episodes_rewards, runtime.
    """
    start_time = time.time()
    Q = defaultdict(float)
    episodes_rewards = []

    for _ in range(num_episodes):
        state = env.reset()
        action = epsilon_greedy_action(Q, env, state, epsilon)
        ep_reward = 0.0
        for _ in range(max_steps):
            next_state, reward, done, _ = env.step(action)
            next_actions = env.get_actions(next_state)
            if next_actions:
                next_action = epsilon_greedy_action(Q, env, next_state, epsilon)
                q_next = Q[(next_state, next_action)]
            else:
                next_action = None
                q_next = 0.0
            Q[(state, action)] += alpha * (
                reward + gamma * q_next - Q[(state, action)]
            )
            ep_reward += reward
            if done:
                break
            state = next_state
            action = next_action
        episodes_rewards.append(ep_reward)

    policy = greedy_policy_from_Q(Q, env)
    runtime = time.time() - start_time
    return {"Q": dict(Q), "policy": policy, "episodes_rewards": episodes_rewards, "runtime": runtime}


def run_td_lambda(env, gamma=0.9, alpha=0.1, lam=0.8, num_episodes=1000, max_steps=200):
    """
    SARSA(lambda) with accumulating eligibility traces.
    Return a dict with keys: V or Q, policy, episodes_rewards, runtime.
    """
    start_time = time.time()
    Q = defaultdict(float)
    epsilon = CONFIG["epsilon"]
    episodes_rewards = []

    for _ in range(num_episodes):
        E = defaultdict(float)
        state = env.reset()
        action = epsilon_greedy_action(Q, env, state, epsilon)
        ep_reward = 0.0

        for _ in range(max_steps):
            next_state, reward, done, _ = env.step(action)
            next_actions = env.get_actions(next_state)
            if next_actions:
                next_action = epsilon_greedy_action(Q, env, next_state, epsilon)
                q_next = Q[(next_state, next_action)]
            else:
                next_action = None
                q_next = 0.0

            td_error = reward + gamma * q_next - Q[(state, action)]
            E[(state, action)] += 1.0

            for sa in list(E.keys()):
                Q[sa] += alpha * td_error * E[sa]
                E[sa] *= gamma * lam
                if E[sa] < 1e-10:
                    del E[sa]

            ep_reward += reward
            if done:
                break
            state = next_state
            action = next_action
        episodes_rewards.append(ep_reward)

    policy = greedy_policy_from_Q(Q, env)
    runtime = time.time() - start_time
    return {"Q": dict(Q), "policy": policy, "episodes_rewards": episodes_rewards, "runtime": runtime}


# ============================================================
# 5. EXPERIMENTS AND COMPARISON
# ============================================================
def run_all_experiments():
    """
    Run all required algorithms on the same environment.
    Each algorithm is seeded identically for fair comparison.
    Return a dictionary: results[algorithm_name] = result_dict.
    """
    env = CustomEnvironment()
    results = {}

    algorithms = [
        ("DP", lambda: run_dynamic_programming(env, gamma=CONFIG["gamma"])),
        (
            "MC",
            lambda: run_monte_carlo(
                env,
                gamma=CONFIG["gamma"],
                epsilon=CONFIG["epsilon"],
                num_episodes=CONFIG["num_episodes"],
                max_steps=CONFIG["max_steps_per_episode"],
            ),
        ),
        (
            "TD0",
            lambda: run_td0(
                env,
                gamma=CONFIG["gamma"],
                alpha=CONFIG["alpha"],
                num_episodes=CONFIG["num_episodes"],
                max_steps=CONFIG["max_steps_per_episode"],
            ),
        ),
        (
            "Q_LEARNING",
            lambda: run_q_learning(
                env,
                gamma=CONFIG["gamma"],
                alpha=CONFIG["alpha"],
                epsilon=CONFIG["epsilon"],
                num_episodes=CONFIG["num_episodes"],
                max_steps=CONFIG["max_steps_per_episode"],
            ),
        ),
        (
            "SARSA",
            lambda: run_sarsa(
                env,
                gamma=CONFIG["gamma"],
                alpha=CONFIG["alpha"],
                epsilon=CONFIG["epsilon"],
                num_episodes=CONFIG["num_episodes"],
                max_steps=CONFIG["max_steps_per_episode"],
            ),
        ),
    ]

    for name, run_fn in algorithms:
        print(f"Running {name}...")
        set_seed(CONFIG["seed"])
        results[name] = run_fn()

    for lam in CONFIG["lambda_values"]:
        name = f"TD_LAMBDA_{lam}"
        print(f"Running {name}...")
        set_seed(CONFIG["seed"])
        results[name] = run_td_lambda(
            env,
            gamma=CONFIG["gamma"],
            alpha=CONFIG["alpha"],
            lam=lam,
            num_episodes=CONFIG["num_episodes"],
            max_steps=CONFIG["max_steps_per_episode"],
        )

    return results


def summarize_results(results):
    """
    Print a clear comparison table.
    Required columns: algorithm, final average reward, convergence estimate, runtime, short conclusion.
    """
    env = CustomEnvironment()

    print("\n" + "=" * 80)
    print("  Assignment 2 Results Summary")
    print(f"  Student: {STUDENT_NAME} ({STUDENT_ID})")
    print(f"  Environment: {ENVIRONMENT_NAME}")
    print("=" * 80)

    header = (
        f"{'Algorithm':<18} {'Avg Reward (last 100)':<24} "
        f"{'Conv. Episode':<16} {'Runtime (s)':<14}"
    )
    print(header)
    print("-" * 72)

    for name, res in results.items():
        rewards = res.get("episodes_rewards", [])
        runtime = res.get("runtime", 0.0)
        avg_last = np.mean(rewards[-100:]) if rewards else 0.0
        conv_ep = estimate_convergence(rewards)
        print(f"{name:<18} {avg_last:<24.4f} {conv_ep:<16} {runtime:<14.4f}")

    print("\n" + "-" * 72)
    print("Policy Evaluation (discounted return, 100 episodes):")
    print(f"{'Algorithm':<18} {'Avg Discounted Return':<24}")
    print("-" * 42)

    for name, res in results.items():
        policy = res.get("policy", {})
        if policy:
            set_seed(999)
            avg_ret = evaluate_policy(
                env,
                policy,
                episodes=CONFIG["eval_episodes"],
                max_steps=CONFIG["max_steps_per_episode"],
                gamma=CONFIG["gamma"],
            )
            print(f"{name:<18} {avg_ret:<24.4f}")

    print("=" * 80)


def plot_results(results):
    """Create required plots. Plots are saved as PNG files."""
    if not CONFIG["make_plots"]:
        return

    window = 50

    # ---- Figure 1: Learning Curves ----
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

    main_colors = {
        "MC": "blue",
        "TD0": "green",
        "Q_LEARNING": "red",
        "SARSA": "purple",
    }
    for name, color in main_colors.items():
        if name in results:
            smoothed = smooth_rewards(results[name]["episodes_rewards"], window)
            ax1.plot(
                range(window, window + len(smoothed)),
                smoothed,
                label=name,
                color=color,
            )

    if "DP" in results:
        dp_avg = np.mean(results["DP"]["episodes_rewards"])
        ax1.axhline(
            y=dp_avg, color="black", linestyle="--", label="DP (optimal)", alpha=0.7
        )

    ax1.set_xlabel("Episode")
    ax1.set_ylabel("Total Reward (smoothed)")
    ax1.set_title("Learning Curves - Main Algorithms")
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    lambda_colors = {0.2: "orange", 0.5: "cyan", 0.8: "magenta"}
    for lam in CONFIG["lambda_values"]:
        key = f"TD_LAMBDA_{lam}"
        if key in results:
            smoothed = smooth_rewards(results[key]["episodes_rewards"], window)
            ax2.plot(
                range(window, window + len(smoothed)),
                smoothed,
                label=f"TD(lambda={lam})",
                color=lambda_colors[lam],
            )

    if "SARSA" in results:
        smoothed = smooth_rewards(results["SARSA"]["episodes_rewards"], window)
        ax2.plot(
            range(window, window + len(smoothed)),
            smoothed,
            label="SARSA (lambda=0)",
            color="purple",
            linestyle="--",
        )

    if "DP" in results:
        dp_avg = np.mean(results["DP"]["episodes_rewards"])
        ax2.axhline(
            y=dp_avg, color="black", linestyle="--", label="DP (optimal)", alpha=0.7
        )

    ax2.set_xlabel("Episode")
    ax2.set_ylabel("Total Reward (smoothed)")
    ax2.set_title("TD(lambda) Comparison")
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig("learning_curves.png", dpi=150, bbox_inches="tight")
    print("Saved: learning_curves.png")

    # ---- Figure 2: Grid Visualization (Value Function + Policy) ----
    env = CustomEnvironment()
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

    if "DP" in results:
        V = results["DP"]["V"]
        policy = results["DP"]["policy"]

        grid_vals = np.full((env.ROWS, env.COLS), np.nan)
        for s in env.get_states():
            grid_vals[s[0], s[1]] = V[s]

        im = ax1.imshow(grid_vals, cmap="RdYlGn", interpolation="nearest")
        plt.colorbar(im, ax=ax1, shrink=0.8)
        for r in range(env.ROWS):
            for c in range(env.COLS):
                if (r, c) in env.WALLS:
                    ax1.text(
                        c, r, "W", ha="center", va="center",
                        fontsize=12, fontweight="bold", color="gray",
                    )
                elif (r, c) in env.TRAPS:
                    ax1.text(
                        c, r, f"T\n{grid_vals[r, c]:.1f}", ha="center", va="center",
                        fontsize=8, color="white",
                    )
                elif (r, c) == env.GOAL:
                    ax1.text(
                        c, r, f"G\n{grid_vals[r, c]:.1f}", ha="center", va="center",
                        fontsize=8,
                    )
                elif (r, c) == env.START:
                    ax1.text(
                        c, r, f"S\n{grid_vals[r, c]:.1f}", ha="center", va="center",
                        fontsize=8,
                    )
                elif not np.isnan(grid_vals[r, c]):
                    ax1.text(
                        c, r, f"{grid_vals[r, c]:.1f}", ha="center", va="center",
                        fontsize=8,
                    )
        ax1.set_title("Value Function (DP)")
        ax1.set_xticks(range(env.COLS))
        ax1.set_yticks(range(env.ROWS))

        grid_bg = np.full((env.ROWS, env.COLS), np.nan)
        for s in env.get_states():
            grid_bg[s[0], s[1]] = V.get(s, 0)
        ax2.imshow(grid_bg, cmap="RdYlGn", interpolation="nearest", alpha=0.3)

        arrow_d = {UP: (0, -0.35), DOWN: (0, 0.35), LEFT: (-0.35, 0), RIGHT: (0.35, 0)}
        for state, action in policy.items():
            r, c = state
            dx, dy = arrow_d[action]
            ax2.annotate(
                "",
                xy=(c + dx, r + dy),
                xytext=(c, r),
                arrowprops=dict(arrowstyle="->", color="black", lw=1.5),
            )

        for r in range(env.ROWS):
            for c in range(env.COLS):
                if (r, c) in env.WALLS:
                    ax2.text(
                        c, r, "W", ha="center", va="center",
                        fontsize=13, fontweight="bold", color="gray",
                    )
                elif (r, c) in env.TRAPS:
                    ax2.text(
                        c, r, "T", ha="center", va="center",
                        fontsize=13, fontweight="bold", color="red",
                    )
                elif (r, c) == env.GOAL:
                    ax2.text(
                        c, r, "G", ha="center", va="center",
                        fontsize=13, fontweight="bold", color="green",
                    )
                elif (r, c) == env.START:
                    ax2.text(
                        c, r, "S", ha="center", va="center",
                        fontsize=13, fontweight="bold", color="blue",
                    )

        ax2.set_title("Optimal Policy (DP)")
        ax2.set_xticks(range(env.COLS))
        ax2.set_yticks(range(env.ROWS))
        ax2.set_xlim(-0.5, env.COLS - 0.5)
        ax2.set_ylim(env.ROWS - 0.5, -0.5)

    plt.tight_layout()
    plt.savefig("grid_visualization.png", dpi=150, bbox_inches="tight")
    print("Saved: grid_visualization.png")

    # ---- Figure 3: Runtime Comparison ----
    fig, ax = plt.subplots(figsize=(10, 5))
    names = list(results.keys())
    runtimes = [results[n]["runtime"] for n in names]
    bars = ax.bar(range(len(names)), runtimes, color="steelblue")
    ax.set_xticks(range(len(names)))
    ax.set_xticklabels(names, rotation=45, ha="right")
    ax.set_ylabel("Runtime (seconds)")
    ax.set_title("Runtime Comparison")
    for bar, rt in zip(bars, runtimes):
        ax.text(
            bar.get_x() + bar.get_width() / 2.0,
            bar.get_height(),
            f"{rt:.3f}s",
            ha="center",
            va="bottom",
            fontsize=9,
        )
    plt.tight_layout()
    plt.savefig("runtime_comparison.png", dpi=150, bbox_inches="tight")
    print("Saved: runtime_comparison.png")


# ============================================================
# 6. WRITTEN ANSWERS INSIDE PY FILE
# ============================================================
WRITTEN_ANSWERS = r"""
1. Environment description:
The Stochastic Treasure Hunt GridWorld is a 6x6 grid where an agent navigates from
start (0,0) to goal (5,5) while avoiding walls and traps. The state space consists
of 32 non-wall cells represented as (row, col) tuples. The action space has 4 actions:
UP, DOWN, LEFT, RIGHT. Transitions are stochastic: 80% probability of moving in the
intended direction, 10% probability for each perpendicular direction. Moving into a
wall or off the grid results in staying in place. Rewards: +10.0 for reaching the
goal, -5.0 for falling into a trap, and -0.1 per step (encouraging efficient paths).
Terminal states are the goal cell (5,5) and two trap cells at (1,5) and (4,1). The
stochastic transitions create meaningful risk near traps, as the agent might slip
sideways into a dangerous cell even with the correct intended action.

2. Convergence:
Dynamic Programming (Value Iteration) converges fastest because it performs full
Bellman backups over the entire state space using the known transition model, reaching
the optimal solution in a fixed number of sweeps independent of episode sampling.
Among model-free methods, Q-Learning and SARSA converge faster than Monte Carlo
because they use bootstrapping (TD updates) which propagates value information after
every step rather than waiting until episode termination. TD(0) also converges
quickly thanks to bootstrapping combined with model-based action selection. Monte
Carlo converges slowest because it must wait for complete episodes to update and
suffers from high variance in return estimates, especially in the early stages when
the exploratory policy rarely reaches the goal. Higher gamma (0.9) causes the agent
to value long-term rewards, leading to better policies but potentially slower
convergence as value propagation takes more iterations. A smaller alpha provides more
stable but slower convergence by dampening update magnitudes. Higher lambda in
TD(lambda) shifts the method from pure bootstrapping (lambda=0) toward full returns
(lambda=1), allowing faster credit assignment for distant rewards at the cost of
increased variance.

3. Delayed rewards:
TD(lambda) with higher lambda values handles delayed rewards best because eligibility
traces allow credit to propagate backward through the trajectory immediately at each
step, without waiting for the episode to end. When the agent reaches the +10 goal,
the TD error is large and positive; eligibility traces carry this signal back to all
recently visited states in proportion to their recency and frequency of visitation.
TD(0) handles delayed rewards poorly because it only updates the value of the
immediately preceding state at each step. Over many episodes, the goal reward
gradually propagates backward one state at a time, making convergence slow when the
reward is many steps away (Manhattan distance ~10 in our grid). Monte Carlo handles
delayed rewards by definition since it uses the complete discounted return G_t, so
every state in the trajectory is updated with the full delayed reward. However, MC
suffers from high variance because G_t depends on the entire trajectory. TD(lambda)
with lambda around 0.8 strikes the best balance: it propagates rewards several steps
back via traces (faster than TD(0)) while still using bootstrapping for stability
(lower variance than MC).

4. Exploration vs exploitation:
Q-Learning is off-policy: it learns the optimal action-value function by always using
max_a Q(s',a') in the update target, regardless of which action was actually taken.
This means it learns about the greedy (optimal) policy while following an exploratory
epsilon-greedy behavior policy. SARSA is on-policy: it updates Q(s,a) using the
Q-value of the (s', a') pair that was actually selected, including exploratory
actions. Near the traps in our grid, SARSA tends to learn more conservative Q-values
because its updates reflect the risk of epsilon-exploration: when the agent is near
(1,5) or (4,1), the 10% random action probability means occasional trap entries, and
SARSA's Q-values incorporate this exploration risk. Q-Learning ignores this risk
because it assumes the optimal (greedy) future behavior. SARSA can outperform
Q-Learning during learning in environments with dangerous states near the optimal
path (the "cliff-walking" effect), because the exploration-aware Q-values lead to
safer trajectories that avoid catastrophic penalties. In our grid, Q-Learning may
suggest paths closer to traps (higher expected reward under the optimal policy), while
SARSA prefers safer detours that avoid the possibility of slipping into traps during
exploration.

5. Computational complexity:
Dynamic Programming has O(|S|^2 * |A|) per iteration and requires storing the full
transition model in memory, but converges in few iterations. Monte Carlo is O(T) per
episode (T = trajectory length) with O(|S| * |A|) memory for return sums and counts.
TD(0), Q-Learning, and SARSA all perform O(1) updates per step with O(|S| * |A|)
memory for the value/Q tables, making them the most efficient per-step methods.
TD(lambda) is the most computationally expensive model-free method because it
maintains eligibility traces for all visited state-action pairs. Each step requires
updating all active traces: O(|active traces|) per step. Higher lambda values cause
traces to decay more slowly (decay factor = gamma * lambda), keeping more traces
active for longer. With lambda=0.8 and gamma=0.9, the effective decay rate is 0.72
per step, meaning traces persist for many steps. In our 32-state, 4-action
environment this overhead is manageable, but in larger environments the cost grows
significantly. Memory usage for TD(lambda) is up to O(|S| * |A|) for the traces
plus O(|S| * |A|) for Q-values. Runtime increases roughly linearly with the average
number of active traces per step.

6. Policy quality:
Dynamic Programming produces the theoretically optimal policy since it solves the
Bellman optimality equation exactly with full model knowledge. Among model-free
methods, Q-Learning tends to converge toward the optimal policy given sufficient
exploration, because the max operator in its update target directly targets the
optimal Q-function. SARSA finds a near-optimal policy that may be slightly more
conservative near traps, reflecting the on-policy learning under epsilon-greedy
exploration. Monte Carlo can also reach the optimal policy but typically requires
more episodes. TD(lambda=0.8) often matches Q-Learning's final policy quality while
converging faster due to superior credit assignment via eligibility traces. In
safety-critical settings, SARSA's slightly suboptimal but more conservative policy
can be preferable: avoiding trap-adjacent cells trades some expected return for
lower variance and fewer catastrophic -5 penalty episodes. The trade-off between
optimality and safety is application-dependent; in our grid, the difference in
average reward between Q-Learning's aggressive and SARSA's cautious policies is
small, but the variance in per-episode returns may differ significantly.

7. Limitations:
(a) Small state space: with only 32 states, tabular methods work well but do not
represent the scalability challenges of real-world problems where function
approximation would be necessary. (b) Fixed hyperparameters: we use constant
epsilon=0.1 and alpha=0.1 throughout training; decaying schedules could improve
both exploration efficiency and convergence stability. (c) Single random seed:
results from one seed may not generalize; averaging over multiple seeds with
confidence intervals would provide more statistically robust comparisons.
(d) Simple reward structure: the binary goal/trap rewards with constant step
penalty do not capture the complexity of multi-objective or shaped reward
functions found in practice. (e) Known transition model for TD(0): our TD(0)
implementation uses the model for policy derivation from V, making it partially
model-based unlike pure model-free Q-Learning and SARSA. (f) The stochastic
transition model is fixed at 80/10/10; varying the stochasticity level would
reveal how each algorithm copes with different degrees of environmental
uncertainty.
"""


# ============================================================
# 7. MAIN
# ============================================================
def main():
    results = run_all_experiments()
    summarize_results(results)
    plot_results(results)
    print("\n=== Written Answers ===")
    print(WRITTEN_ANSWERS)


if __name__ == "__main__":
    main()
